# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtCore import QTimer
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication
import manual_ui
from enum import Enum
from time import sleep
import subprocess
import socket
import json
import threading
import detection
from socket_thread import SocketThread

x_degree_val = 0
y_degree_val = 0
lift_val = 0
motor_speed_val = 0
period = 1
launch_en = 1
latest_target  = 0
target_lock = threading.Lock()

class Mode(Enum):
    MANUAL = 1
    AUTO = 2
    HOME = 3

class Status(Enum):
    STOP = 1
    START = 2

current_mode = Mode.MANUAL
current_status = Status.STOP

def handle_socket_data(ui, row, col, targets):
    global latest_target
    with target_lock:
        latest_target = targets

class Ui_MainWindow(object):
    def __init__(self, arduino1, arduino2):
        self.arduino1 = arduino1
        self.arduino2 = arduino2
        with open("config.json", "r") as f:
            self.positions = json.load(f)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(350, 583)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.manualButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.manualButton.setGeometry(QtCore.QRect(60, 40, 75, 24))
        self.manualButton.setObjectName("manualButton")
        self.autoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.autoButton.setGeometry(QtCore.QRect(150, 40, 75, 24))
        self.autoButton.setObjectName("autoButton")
        self.homeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(260, 40, 75, 24))
        self.homeButton.setObjectName("homeButton")
        self.feederButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.feederButton.setGeometry(QtCore.QRect(250, 300, 75, 50))
        self.feederButton.setObjectName("feederButton")
        self.upButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(120, 160, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.upButton.setFont(font)
        self.upButton.setObjectName("upButton")
        self.downButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(120, 260, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.downButton.setFont(font)
        self.downButton.setObjectName("downButton")
        self.rightButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(180, 220, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.rightButton.setFont(font)
        self.rightButton.setObjectName("rightButton")
        self.leftButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(50, 220, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.leftButton.setFont(font)
        self.leftButton.setObjectName("leftButton")
        self.degreeText = QtWidgets.QLabel(parent=self.centralwidget)
        self.degreeText.setGeometry(QtCore.QRect(120, 230, 49, 16))
        self.degreeText.setObjectName("degreeText")
        self.degreeText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.liftUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.liftUp.setGeometry(QtCore.QRect(80, 350, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.liftUp.setFont(font)
        self.liftUp.setObjectName("liftUp")
        self.liftText = QtWidgets.QLabel(parent=self.centralwidget)
        self.liftText.setGeometry(QtCore.QRect(80, 430, 49, 16))
        self.liftText.setObjectName("liftText")
        self.liftText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.liftDown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.liftDown.setGeometry(QtCore.QRect(80, 460, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.liftDown.setFont(font)
        self.liftDown.setObjectName("liftDown")
        self.motorSpeedUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.motorSpeedUp.setGeometry(QtCore.QRect(160, 350, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.motorSpeedUp.setFont(font)
        self.motorSpeedUp.setObjectName("motorSpeedUp")
        self.motorSpeedText = QtWidgets.QLabel(parent=self.centralwidget)
        self.motorSpeedText.setGeometry(QtCore.QRect(146, 430, 80, 16))
        self.motorSpeedText.setObjectName("motorSpeedText")
        self.motorSpeedText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.motorSpeedDown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.motorSpeedDown.setGeometry(QtCore.QRect(160, 460, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.motorSpeedDown.setFont(font)
        self.motorSpeedDown.setObjectName("motorSpeedDown")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(60, 110, 75, 24))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(150, 110, 75, 24))
        self.stopButton.setObjectName("stopButton")
        self.inTimeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inTimeButton.setGeometry(QtCore.QRect(250, 130, 40, 24))
        self.inTimeButton.setObjectName("inTimeButton")
        self.decTimeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.decTimeButton.setGeometry(QtCore.QRect(300, 130, 40, 24))
        self.decTimeButton.setObjectName("decTimeButton")
        self.periodText = QtWidgets.QLabel(parent=self.centralwidget)
        self.periodText.setGeometry(QtCore.QRect(270, 90, 50, 16))
        self.periodText.setObjectName("periodText")
        self.periodText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 293, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.manualButton.clicked.connect(self.handle_manual)
        self.autoButton.clicked.connect(self.handle_auto)
        self.homeButton.clicked.connect(self.handle_home)
        self.feederButton.clicked.connect(self.handle_feeder_rotate)
        self.startButton.clicked.connect(self.handle_start)
        self.stopButton.clicked.connect(self.handle_stop)
        self.inTimeButton.clicked.connect(self.handle_inTime)
        self.decTimeButton.clicked.connect(self.handle_decTime)
        self.upButton.clicked.connect(self.handle_up)
        self.downButton.clicked.connect(self.handle_down)
        self.leftButton.clicked.connect(self.handle_left)
        self.rightButton.clicked.connect(self.handle_right)
        self.liftUp.clicked.connect(self.handle_lift_up)
        self.liftDown.clicked.connect(self.handle_lift_down)
        self.motorSpeedUp.clicked.connect(self.handle_motor_speed_up)
        self.motorSpeedDown.clicked.connect(self.handle_motor_speed_down)

        self.liftValueLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.liftValueLabel.setGeometry(QtCore.QRect(30, 430, 40, 20))  # (x, y, width, height)
        self.liftValueLabel.setText("0")  # Initial value
        self.liftValueLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)  # Show as a box
        self.liftValueLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.motorSpeedValueLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.motorSpeedValueLabel.setGeometry(QtCore.QRect(230, 430, 40, 20))  # Adjusted position
        self.motorSpeedValueLabel.setText("0")  # Initial value
        self.motorSpeedValueLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)  # Show as a box
        self.motorSpeedValueLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.xValueText = QtWidgets.QLabel(parent=self.centralwidget)
        self.xValueText.setGeometry(QtCore.QRect(250, 210, 30, 20))
        self.xValueText.setObjectName("x")
        self.xValueText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.xValueLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.xValueLabel.setGeometry(QtCore.QRect(250, 230, 30, 20))  # Adjusted position
        self.xValueLabel.setText("0")  # Initial value
        self.xValueLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)  # Show as a box
        self.xValueLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.yValueText = QtWidgets.QLabel(parent=self.centralwidget)
        self.yValueText.setGeometry(QtCore.QRect(290, 210, 30, 20))
        self.yValueText.setObjectName("y")
        self.yValueText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.yValueLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.yValueLabel.setGeometry(QtCore.QRect(290, 230, 30, 20))  # Adjusted position
        self.yValueLabel.setText("0")  # Initial value
        self.yValueLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)  # Show as a box
        self.yValueLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.periodLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.periodLabel.setGeometry(QtCore.QRect(285, 110, 20, 16))  # Adjusted position
        self.periodLabel.setText("1.5")  # Initial value
        self.periodLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)  # Show as a box
        self.periodLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)


        #set button colour
        self.manualButton.setStyleSheet("background-color: lightgreen")
        self.stopButton.setStyleSheet("background-color: lightgreen")

        self.logoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.logoPixmap = QtGui.QPixmap("js_logo.png")
        self.logoLabel.setPixmap(self.logoPixmap)
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setFixedSize(60, 60)
        self.logoLabel.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.resizeEvent = self.on_resize

        # Timer to check latest target every 50ms
        self.target_timer = QTimer()
        self.target_timer.timeout.connect(self.process_latest_target)
        self.target_timer.start(50)

    def on_resize(self, event):
        window_width = self.centralwidget.width()
        window_height = self.centralwidget.height()
        self.logoLabel.move(window_width - self.logoLabel.width() - 10,
                            window_height - self.logoLabel.height() - 10)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Badminton Machine Controller"))
        self.manualButton.setText(_translate("MainWindow", "Manual"))
        self.autoButton.setText(_translate("MainWindow", "Auto"))
        self.homeButton.setText(_translate("MainWindow", "Homing"))
        self.feederButton.setText(_translate("MainWindow", "⟳"))
        self.feederButton.setStyleSheet("font-size: 20pt; font-weight: bold;") 
        self.upButton.setText(_translate("MainWindow", "↑"))
        self.downButton.setText(_translate("MainWindow", "↓"))
        self.rightButton.setText(_translate("MainWindow", "→"))
        self.leftButton.setText(_translate("MainWindow", "←"))
        self.degreeText.setText(_translate("MainWindow", "degree"))
        self.liftUp.setText(_translate("MainWindow", "↑"))
        self.liftText.setText(_translate("MainWindow", "lift"))
        self.liftDown.setText(_translate("MainWindow", "↓"))
        self.motorSpeedUp.setText(_translate("MainWindow", "↑"))
        self.motorSpeedText.setText(_translate("MainWindow", "motor speed"))
        self.motorSpeedDown.setText(_translate("MainWindow", "↓"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.inTimeButton.setText(_translate("MainWindow", "+"))
        self.decTimeButton.setText(_translate("MainWindow", "-"))
        self.xValueText.setText(_translate("MainWindow", "x"))
        self.yValueText.setText(_translate("MainWindow", "y"))
        self.periodText.setText(_translate("MainWindow", "Period"))

    def disable_all_buttons_except_stop(self):
        for btn in [self.manualButton, self.autoButton, self.homeButton, self.startButton,
                    self.upButton, self.downButton, self.leftButton, self.rightButton,
                    self.liftUp, self.liftDown, self.motorSpeedUp, self.motorSpeedDown,
                    self.inTimeButton, self.decTimeButton]:
            btn.setDisabled(True)
        self.stopButton.setDisabled(False)  # Keep Stop button active

    def disable_all_buttons(self):
        for btn in [self.manualButton, self.autoButton, self.homeButton, self.startButton, 
                    self.stopButton, self.upButton, self.downButton, self.leftButton, 
                    self.rightButton, self.liftUp, self.liftDown, self.motorSpeedUp, 
                    self.motorSpeedDown, self.inTimeButton, self.decTimeButton]:
            btn.setDisabled(True)

    def enable_all_buttons(self):
        for btn in [self.manualButton, self.autoButton, self.homeButton, self.startButton,
                    self.upButton, self.downButton, self.leftButton, self.rightButton,
                    self.liftUp, self.liftDown, self.motorSpeedUp, self.motorSpeedDown,
                    self.inTimeButton, self.decTimeButton, self.stopButton]:
            btn.setDisabled(False)

    def handle_manual(self):
        global current_mode
        current_mode = Mode.MANUAL
        print("Manual button clicked")
        self.manualButton.setStyleSheet("background-color: lightgreen")
        self.autoButton.setStyleSheet("background-color: None")  # Reset

    def handle_auto(self):
        global current_mode
        current_mode = Mode.AUTO
        print("Auto button clicked")
        self.autoButton.setStyleSheet("background-color: lightgreen")
        self.manualButton.setStyleSheet("background-color: None")  # Reset

    def handle_home(self):
        print("Homing button clicked")
        if current_status == Status.STOP:
            for btn in [self.manualButton, self.autoButton, self.startButton,
                    self.stopButton]:
                btn.setStyleSheet("")
            self.homeButton.setStyleSheet("background-color: lightgreen")
            self.disable_all_buttons()
            QApplication.processEvents()
            current_mode = Mode.HOME
            sys2.main(self.arduino2, "motor_home")
            global y_degree_val
            y_degree_val = 0
            global lift_val
            lift_val = 0
            self.liftValueLabel.setText(str(lift_val)) 
            sys1.main(self.arduino1, "motor_home")
            global x_degree_val
            x_degree_val = 0
            self.xValueLabel.setText(str(x_degree_val))
            self.yValueLabel.setText(str(y_degree_val))
            self.enable_all_buttons()
            self.homeButton.setStyleSheet("")
            self.stopButton.setStyleSheet("background-color: lightgreen")
            print(current_mode)

    def handle_feeder_rotate(self):
        sys2.main(self.arduino2, "move_motor")
        print("Feeder button clicked")

    def on_motor_speed_changed(self, speed):
        global motor_speed_val

        motor_speed_val = speed
        self.motorSpeedValueLabel.setText(str(speed))

        print("[MAIN] Motor speed updated:", speed)

    def PosYChanged(self, y_value):
        global y_degree_val

        y_degree_val = y_value
        self.yValueLabel.setText(str(y_degree_val))

        print("[MAIN] y_degree_val updated:", y_value)

    def PosXChanged(self, x_value):
        global x_degree_val

        x_degree_val = x_value
        self.xValueLabel.setText(str(x_degree_val))

        print("[MAIN] x_degree_val updated:", x_value)

    def handle_start(self):
        global current_status
        self.startButton.setStyleSheet("background-color: lightgreen")
        self.stopButton.setStyleSheet("")  # Reset
        
        if current_mode == Mode.AUTO and current_status == Status.STOP:
            self.disable_all_buttons_except_stop()
            current_status = Status.START

            self.statusbar.showMessage("Running (AUTO mode)")

            # Start socket
            self.socket_thread = SocketThread()
            self.socket_thread.data_received.connect(
                lambda r, c, t: handle_socket_data(self, r, c, t)
            )
            self.socket_thread.start()
            print("[MAIN] Socket started")

            # Start detection
            self.detection_thread = threading.Thread(
                target=detection.main, daemon=True
            )
            self.detection_thread.start()
            print("[MAIN] Detection started")
            
        elif current_mode == Mode.MANUAL and current_status == Status.STOP:
            self.disable_all_buttons_except_stop()
            current_status = Status.START
            self.manual_window, self.manual_ui = manual_ui.main(arduino1, arduino2, 0)
            self.manual_window.PosXChanged.connect(
                self.PosXChanged
            )
            self.manual_window.PosYChanged.connect(
                self.PosYChanged
            )
            self.manual_window.motorSpeedChanged.connect(
                self.on_motor_speed_changed
            )
            
        else:
            current_status = Status.START
        
    def handle_stop(self):
        global current_status
        if current_status == Status.START and current_mode == Mode.AUTO:
            if hasattr(self, "socket_thread") and self.socket_thread:
                self.socket_thread.stop()
                self.socket_thread = None
                print("[MAIN] Socket stopped")

        elif current_status == Status.START and current_mode == Mode.MANUAL:
            if hasattr(self, "manual_window") and self.manual_window is not None:
                self.manual_window.close()  
                self.manual_window = None   
                print("Manual window closed.")
        current_status = Status.STOP
        self.stopButton.setStyleSheet("background-color: lightgreen")
        self.startButton.setStyleSheet("background-color: None")  # Reset
        self.enable_all_buttons()
        print("Stop button clicked")

    def handle_up(self):
        global y_degree_val
        if y_degree_val < 21:
            y_degree_val += 1
            self.yValueLabel.setText(str(y_degree_val))
            cmd = "stepperAngle_" + str(y_degree_val)
            sys2.main(self.arduino2, cmd)
        print("Up button clicked")

    def handle_down(self):
        global y_degree_val
        if y_degree_val > 0:
            y_degree_val -= 1
            self.yValueLabel.setText(str(y_degree_val)) 
            cmd = "stepperAngle_" + str(y_degree_val)
            sys2.main(self.arduino2, cmd)
        print("Down button clicked")

    def handle_left(self):
        global x_degree_val
        if x_degree_val > -50:
            x_degree_val -= 1
            self.xValueLabel.setText(str(x_degree_val)) 
            cmd = "motorLeftRight_" + str(x_degree_val)
            sys1.main(self.arduino1, cmd)
        print("Left button clicked")

    def handle_right(self):
        global x_degree_val
        if x_degree_val < 50:
            x_degree_val += 1
            self.xValueLabel.setText(str(x_degree_val)) 
            cmd = "motorLeftRight_" + str(x_degree_val)
            sys1.main(self.arduino1, cmd)
        print("Right button clicked")

    def handle_lift_up(self):
        global lift_val
        if lift_val < 45:
            lift_val += 1
            self.liftValueLabel.setText(str(lift_val)) 
            sys1.main(self.arduino1, "motor_up")
        print("Lift Up clicked")

    def handle_lift_down(self):
        global lift_val 
        if lift_val > 0: #0
            lift_val -= 1
            self.liftValueLabel.setText(str(lift_val)) 
            sys1.main(self.arduino1, "motor_down")
        print("Lift Down clicked")

    def handle_motor_speed_up(self):
        global motor_speed_val
        if motor_speed_val < 255:
            motor_speed_val += 5
            self.motorSpeedValueLabel.setText(str(motor_speed_val))
            msg = ("motorSpeed_") + str(motor_speed_val)
            sys2.main(self.arduino2, msg)
        print("Motor Speed Up clicked")

    def handle_motor_speed_down(self):
        global motor_speed_val
        if motor_speed_val > 0:
            motor_speed_val -= 5
            self.motorSpeedValueLabel.setText(str(motor_speed_val)) 
            msg = ("motorSpeed_") + str(motor_speed_val)
            sys2.main(self.arduino2, msg)
        print("Motor Speed Down clicked")

    def handle_inTime(self):
        global period
        if period < 5:
            period += 1
            if period == 1:
                self.periodLabel.setText(str(period + 0.5))
            else:
                self.periodLabel.setText(str(period))
            cmd = "period_" + str(period)
            sys2.main(self.arduino2, cmd)
        print("Increase time clicked")

    def handle_decTime(self):
        global period
        if period > 1:
            period -= 1
            if period == 1:
                self.periodLabel.setText(str(period + 0.5))
            else:
                self.periodLabel.setText(str(period))
            cmd = "period_" + str(period)
            sys2.main(self.arduino2, cmd)
        print("Decrease time clicked")

    def resetAutoMode(self):
        sys2.main(self.arduino2, "resetAutoMode_0")

    def autoMode(self, target_to_process):
        sys2.main(self.arduino2, f"autoMode_{target_to_process}")

    def handle_position(self, pos):
        key = str(pos)
        if not hasattr(self, "positions"):
            print("[ERROR] positions not loaded")
            return

        if key not in self.positions:
            print(f"[ERROR] Invalid position {pos}")
            return

        cfg = self.positions[key]
        v = cfg["vertical_angle"]
        h = cfg["horizontal_angle"]
        s = cfg["motor_speed"]

        print(f"[POS {pos}] V={v} H={h} S={s}")

        # Uncomment when ready
        # sys2.main(self.arduino2, f"movePosY_{v}")
        # sys1.main(self.arduino1, f"motorLeftRight_{h}")
        # sys2.main(self.arduino2, f"motorSpeed_{s}")

        print(f"[POS {pos}] V={v} H={h} S={s}")

    def process_latest_target(self):
        global latest_target
        global launch_en
        with target_lock:
            if latest_target == 0:
                return
            target_to_process = latest_target
            latest_target = 0  # reset after taking the latest
        print("latest_target: ", target_to_process)
        if 1 <= target_to_process <= 9:
            if launch_en == 1:
                launch_en = 0
                ui.handle_position(target_to_process)
                ui.autoMode(target_to_process)
                launch_en = 1

if __name__ == "__main__":
    import sys
    import sys1
    import sys2
    arduino1 = sys1.sys1_init()
    arduino2 = sys2.sys2_init()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(arduino1, arduino2)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())