# Form implementation generated from reading ui file 'manual.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys1
import sys2

class Ui_MainWindow(object):
    def __init__(self, arduino1, arduino2):
        self.arduino1 = arduino1
        self.arduino2 = arduino2

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(328, 440)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(20, 20, 81, 71))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(120, 20, 81, 71))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(220, 20, 81, 71))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(20, 120, 81, 71))
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(120, 120, 81, 71))
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(220, 120, 81, 71))
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(20, 220, 81, 71))
        self.pushButton7.setObjectName("pushButton7")
        self.pushButton8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton8.setGeometry(QtCore.QRect(120, 220, 81, 71))
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton9.setGeometry(QtCore.QRect(220, 220, 81, 71))
        self.pushButton9.setObjectName("pushButton9")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(20, 320, 81, 71))
        self.startButton.setObjectName("startButton")
        self.randomButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.randomButton.setGeometry(QtCore.QRect(120, 320, 81, 71))
        self.randomButton.setObjectName("randomButton")
        self.launch1Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.launch1Button.setGeometry(QtCore.QRect(220, 320, 81, 71))
        self.launch1Button.setObjectName("launch1Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 328, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton1.clicked.connect(self.handle_1)
        self.pushButton2.clicked.connect(self.handle_2)
        self.pushButton3.clicked.connect(self.handle_3)
        self.pushButton4.clicked.connect(self.handle_4)
        self.pushButton5.clicked.connect(self.handle_5)
        self.pushButton6.clicked.connect(self.handle_6)
        self.pushButton7.clicked.connect(self.handle_7)
        self.pushButton8.clicked.connect(self.handle_8)
        self.pushButton9.clicked.connect(self.handle_9)
        self.startButton.clicked.connect(self.handle_start)
        self.randomButton.clicked.connect(self.handle_random)
        self.launch1Button.clicked.connect(self.handle_launch1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Manual Mode"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton2.setText(_translate("MainWindow", "2"))
        self.pushButton3.setText(_translate("MainWindow", "3"))
        self.pushButton4.setText(_translate("MainWindow", "4"))
        self.pushButton5.setText(_translate("MainWindow", "5"))
        self.pushButton6.setText(_translate("MainWindow", "6"))
        self.pushButton7.setText(_translate("MainWindow", "7"))
        self.pushButton8.setText(_translate("MainWindow", "8"))
        self.pushButton9.setText(_translate("MainWindow", "9"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.randomButton.setText(_translate("MainWindow", "Random"))
        self.launch1Button.setText(_translate("MainWindow", "Launch 1"))

    def change_button_colour(self, button):
        for btn in [self.pushButton1, self.pushButton2, self.pushButton3,
                self.pushButton4, self.pushButton5, self.pushButton6,
                self.pushButton7, self.pushButton8, self.pushButton9,
                self.startButton, self.randomButton, self.launch1Button]:
            btn.setStyleSheet("")
        button.setStyleSheet("background-color: lightgreen")

    def reset_button_colour(self):
        for btn in [self.pushButton1, self.pushButton2, self.pushButton3,
                self.pushButton4, self.pushButton5, self.pushButton6,
                self.pushButton7, self.pushButton8, self.pushButton9,
                self.startButton, self.randomButton, self.launch1Button]:
            btn.setStyleSheet("")

    def handle_1(self):
        button = self.pushButton1
        self.change_button_colour(button)
        sys1.main(self.arduino1, "motor_up")  # now use self.arduino
        print("1 button clicked")
    
    def handle_2(self):
        button = self.pushButton2
        self.change_button_colour(button)
        print("2 button clicked")
    
    def handle_3(self):
        button = self.pushButton3
        self.change_button_colour(button)
        print("3 button clicked")
    
    def handle_4(self):
        button = self.pushButton4
        self.change_button_colour(button)
        print("4 button clicked")

    def handle_5(self):
        button = self.pushButton5
        self.change_button_colour(button)
        print("5 button clicked")
    
    def handle_6(self):
        button = self.pushButton6
        self.change_button_colour(button)
        print("6 button clicked")
    
    def handle_7(self):
        button = self.pushButton7
        self.change_button_colour(button)
        print("7 button clicked")
    
    def handle_8(self):
        button = self.pushButton8
        self.change_button_colour(button)
        print("8 button clicked")
    
    def handle_9(self):
        button = self.pushButton9
        self.change_button_colour(button)
        print("9 button clicked")
    
    def handle_start(self):
        button = self.startButton
        self.change_button_colour(button)
        QtWidgets.QApplication.processEvents() 
        print("start button clicked")
        sys2.main(self.arduino2, "system_all") 
        self.reset_button_colour()

    def handle_random(self):
        button = self.randomButton
        self.change_button_colour(button)
        print("random button clicked")

    def handle_launch1(self):
        button = self.launch1Button
        self.change_button_colour(button)
        QtWidgets.QApplication.processEvents() 
        print("launch1 button clicked")
        sys2.main(self.arduino2, "system_one") 
        self.reset_button_colour()

def main(arduino1, arduino2):
    app = QtWidgets.QApplication.instance()
    if app is None:
        app = QtWidgets.QApplication([])

    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(arduino1, arduino2)  # ← pass arduino here
    ui.setupUi(window)
    window.show()

    return window, ui
